name: flutter_cupertino_date_picker
description: Flutter cupertino date picker. Display DatePicker in iOS style. Support both Android and iOS platform.
version: 1.1.0
homepage: https://github.com/wuzhendev/flutter-cupertino-date-picker

dependencies:
  flutter:
    sdk: flutter

flutter:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.4.1 <2.0.0"
